samples_file: resources/samples.txt
metadata: 
    MSK: resources/metadata.MSK.tsv
    NYGC: ../data/svs/nygc
    Broad: ../data/svs/broad/All_Pairs.dRanger_etc.filtered_SV.138_pairs.with_tumor_submitter_id.in_bedpe_format.tsv
ref:
    genome_version: "hg38"
    gtf: ../data/gencode/gencode.v45.basic.annotation.gtf.gz
    fai: ../assemblies/WGS-GRCh38-GDC/human/GRCh38.d1.vd1.fa.fai
image:
    survivor: resources/survivor.sif
log_dir: logs
tmp_dir: tmp

