default-resources:
  - partition=componc_cpu
  - mem_mb=4096
restart-times: 3
max-jobs-per-second: 50
max-status-checks-per-second: 1
local-cores: 1
jobs: 500
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
use-singularity: True
